"""Added product_price and product_quantity in product

Revision ID: c6e560bda3d2
Revises: fd2379e70a12
Create Date: 2021-07-22 10:00:57.068024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6e560bda3d2'
down_revision = 'fd2379e70a12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('product_price', sa.INTEGER(), nullable=True))
    op.add_column('product', sa.Column('product_quantity', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'product_quantity')
    op.drop_column('product', 'product_price')
    # ### end Alembic commands ###
