"""Initial Migration

Revision ID: fd2379e70a12
Revises: 
Create Date: 2021-07-21 23:10:16.804351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd2379e70a12'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('category_id', sa.INTEGER(), nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.Column('category_desc', sa.String(length=1000), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('category_parent_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['category_parent_id'], ['category.category_id'], name='FK__category__category__category_parent_id'),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('product',
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('product_name', sa.String(length=100), nullable=False),
    sa.Column('product_desc', sa.String(length=1000), nullable=True),
    sa.Column('product_image_URI', sa.String(length=1000), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('category_to_product_map',
    sa.Column('cat_to_product_map', sa.INTEGER(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('category_id', sa.INTEGER(), nullable=True),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], name='FK__category_to_product_map__category__category_id'),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], name='FK__category_to_product_map__product__product_id'),
    sa.PrimaryKeyConstraint('cat_to_product_map')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category_to_product_map')
    op.drop_table('product')
    op.drop_table('category')
    # ### end Alembic commands ###
